public class fakeZoomMeetingCreated {

    //javascript jsondata.payload.object.topic
    //reactjs-typescript sablon
    //
    
    public class jsonNode{
        public string event;
        public string event_ts;
        public payloadNode payload;
    }
    public class payloadNode{
        public string account_id;
        public string operator;
        public string operator_id;
        public string operation;
    }
}